Export NewItem function
jellydator/ttlcache pull request #151
Opened 2024-09-20 07:50 UTC by hasfjord

There might be multiple reasons for creating an Item object manually. Now the only way of creating such an object is to add it to the cache, which might not always be ideal.
My use-case is allowing a workaround for loader error handling.

By storing the error in the value it could be inspected by the caller of the get function.

Cached function:
```
type cachedValue struct {
	usefulString string
	Err          error
}
```
Loader:
```
loader := ttlcache.LoaderFunc[string, *cachedValue](
		func(c *ttlcache.Cache[string, *cachedValue], key string) *ttlcache.Item[string, *cachedValue] {
			v, err := SomethingThatCouldFail()
			if err != nil {
				return ttlcache.NewItem(key, cachedValue{"", err}, 0, false)
			}
			return c.Set(key, v, 1*time.Hour)
		})
```
Cache setup:
```
cache := ttlcache.New(
		ttlcache.WithTTL[string, *cachedValue](1*time.Hour),
		ttlcache.WithLoader(loader),
	)
```
Get call:
```
// Get the value from the cache
item := cache.Get("key").Value()
if item.Err != nil {
	//handle error
}
// use item.Value().usefulString
```

I would prefer the loader function returning an error in addition to the error, but that would break the current api contract.

2024-09-20 17:09 UTC, swithek requested changes
I quite like the loader error workaround in your example. There's just one small change that we need to make:

2024-09-20 17:09 UTC, swithek commented on item_test.go
>  func Test_newItem(t *testing.T) {
```suggestion
func Test_NewItem(t *testing.T) {
```

2024-09-20 17:11 UTC, swithek commented
Regarding the loader interface and errors: we have [this issue](https://github.com/jellydator/ttlcache/issues/120), feel free to upvote it/share your ideas there as well.

2024-09-23 07:12 UTC, hasfjord commented on item_test.go
>  func Test_newItem(t *testing.T) {
Sure, that makes sense. Amended.

2024-09-23 11:31 UTC, swithek approved these changes
Thank you for your contribution @hasfjord.

2024-09-23 11:31 UTC, merged